### ISSUE TITLE
 Bitmap is not working 

### ISSUE THREAD

**Issue by salahsnz** [AuliaVailo/flutter_pax_printer_utility#1]
how do i print image from asset

**Comment by MAHAulia** [comment]
hello, maybe you can try using the printBitmap(Bitmap bitmap) function

**Comment by salahsnz** [comment]
Bitmap bitmap = await Bitmap.fromProvider(NetworkImage("http://pudim.com.br/pudim.jpg"));
   // Bitmap bitmap = Bitmap.blank(200, 300);
    await FlutterPaxPrinterUtility.printBitmap(bitmap);


I have tried, but it is crashing

**Comment by MAHAulia** [comment]
hmmm, oke 
let me check this bug, thanks for your report...

**Comment by salahsnz** [comment]
please let me know once done

**Comment by salahsnz** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument: Instance of 'Bitmap'

**Comment by MAHAulia** [comment]
hey I'm trying to fix this problem by adding two functions to print image from asset or image from url.

And I have released it on pub.dev, please try using version 0.1.0

**Comment by salahsnz** [comment]
Error: Couldn't resolve the package 'bitmap' in 'package:bitmap/bitmap.dart'.
/C:/src/flutter/packages/flutter/lib/src/services/message_codecs.dart:11:8: Error: Not found: 'package:bitmap/bitmap.dart'
import 'package:bitmap/bitmap.dart';


is it required bitmap lib

**Comment by salahsnz** [comment]
Thanks for the help printing image is working...

can u also check why the text size not changing
