### ISSUE TITLE
Cannot set font size

### ISSUE THREAD

**Issue by PhilipPurwoko** [AuliaVailo/flutter_pax_printer_utility#2]
Hello, currently I am working on a project and using your package. 
According to the [PAX Device SDK documentation](https://docs.hips.com/docs/pax-a920) we can set font size via below configuration.

> **asciiFontType**
> - EFontTypeAscii EFontTypeAscii.FONT_8_16:8x16 font (Basic)
> - EFontTypeAscii.FONT_12_24:12x24 font (Basic)
> - EFontTypeAscii.FONT_8_32:8x16 font (enlarge vertically)
> - EFontTypeAscii.FONT_12_48:12x24 font (enlarge vertically)
> - EFontTypeAscii.FONT_16_16:8x16 font (enlarge horizontally)
> - EFontTypeAscii.FONT_24_24:12x24 font (enlarge horizontally)
> - EFontTypeAscii.FONT_16_32:8x16 font (enlarge on both levels)
> - EFontTypeAscii.FONT_24_48:12x24 font (enlarge on both levels)
 
> **fontTypeExtCode**
> - EFontTypeExtCode font set for extended code characters FONT_16_16 -16x16 font (Basic)
> - FONT_24_24 -24x24 font (Basic)
> - FONT_16_32 -16x16 font (enlarge vertically)
> - FONT_24_48 -24x24 font (enlarge vertically)
> - FONT_48_24 -16x16 font (enlarge horizontally)
> - FONT_32_32 -24x24 font (enlarge horizontally)
> - FONT_48_24 -16x16 font (enlarge on both levels) FONT_48_48 -24x24 font (enlarge on both levels)

On this package we can set them via `fontSet` method

```dart
await FlutterPaxPrinterUtility.fontSet(EFontTypeAscii.FONT_24_48, EFontTypeExtCode.FONT_48_48);
```

But nothing changes. The font still default and small. Can anyone help ? I will provide more information if necessary.

Thanks

**Comment by PhilipPurwoko** [comment]
Sorry for the misconception. I thought this function was to set the font size

**Comment by salahsnz** [comment]
what was the fix?

**Comment by PhilipPurwoko** [comment]
You forgot to change the font size on java side.
https://github.com/AuliaVailo/flutter_pax_printer_utility/pull/3/commits/53e9c036209fa3a46e222f9310c5eee5678550a0#diff-1a74983018c9e2daa4e4574f9b8b6fd8ee9360c209396d84ceab7f75352ea01b

Also don't override `toString()` method because we need it for comparison
https://github.com/AuliaVailo/flutter_pax_printer_utility/pull/3/commits/64c9c6e013c0bf7048ac4c20a9eed89fb2decbef#diff-889768c9dfc21bf1088f1083a675174163dc5a281620060d0f6819d1fa4bf858
