### ISSUE TITLE
it is not working on a production app but running on debug mode. Help me out please..

### ISSUE THREAD

**Issue by abhishekr77** [AuliaVailo/flutter_pax_printer_utility#8]
<img width="1701" alt="Screenshot 2022-12-02 at 12 09 57 AM" src="https://user-images.githubusercontent.com/45325626/205144578-c1654ad4-efca-4758-96a7-e1e9f1ae91c4.png">

**Comment by abanoubEssam** [comment]
also with me @abhishekr77

**Comment by MAHAulia** [comment]
hallo @abhishekr77 , @abanoubEssam  :)

i try to fix this issue, and i just found the solution.

please add minify and shrink to false on build.gradle like this

![image](https://user-images.githubusercontent.com/40622034/224090905-5995cfa7-b8f2-4094-a74d-35b2ac1a7998.png)

hope, this fix the issue
